version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: .
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
